server:
  port: 8080
  error:
      include-message: always
spring:


  datasource:
    username: root
    password: Greewka1986.
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 30
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  output:
      ansi:
        enabled: always

  jpa:
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

        jdbc:
          batch_size: 1000
          batch_versioned_data: true

hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true
      useUnicode: true
      characterEncoding: utf-8
      dialect: org.hibernate.dialect.MySQL8Dialect
jsoup-setting:
  jsoup:
    userAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0
    referrer: https://www.google.com
    timeout: 5_000
    ignoreHttpErrors: true
    followRedirects: false

indexing-settings:
  sites:

    - url: https://www.svetlovka.ru/
      name: Светловка
    - url: https://dombulgakova.ru/
      name: Home of Bulgakov
    - url: https://nikoartgallery.com/
      name: Niko Gallery

user-settings:
  clear-site-if-not-exists: true
  delete-next-level-pages: true
  exclude-most-frequently-lemmas: true
  return-zero-pages-if-not-all-lemmas-found: true
  logging-enable: false

